<?php
define('ONSCROLL_URL', 'http://cdn.onscroll.com/onscroll.ms.js');

/**
 * Implements hook_permission().
 */
function onscroll_permission() {
  return array(
    'administer onscroll' => array(
      'title' => t('Administer onscroll'),
      'description' => t('Administer account settings and visibility of onscroll on your site.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function onscroll_menu() {
  $items['admin/config/system/onscroll'] = array(
    'title' => 'OnScroll',
    'description' => 'Configure onscroll blocks on your website.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('onscroll_admin_settings_form'),
    'access arguments' => array('administer onscroll'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'admin.inc',
  );

  return $items;
}

/**
 * Implementation of hook_help().
 */
function onscroll_help($path, $arg) {
  switch ($path) {
    case 'admin/config/system/onscroll':
      return t('<a href="@url">OnScroll</a> determines the most appropriate time to deliver a viewable ad based on user behaviour.', array('@url' => 'http://www.onscroll.com/'));
  }
}

/**
 * Implements hook_page_alter().
 */
function onscroll_page_alter(&$page) {

  if (!path_is_admin(current_path())) {
    if (variable_get('onscroll_enabled')) {
      // Add inline script.
      $script = 'var onScrOll=new Object();' . PHP_EOL;
      $script .= 'onScrOll.code="' . variable_get('onscroll_code', '') . '";';
      $script .= 'onScrOll.margin=' . variable_get('onscroll_margin', 600) . ';';
      $script .= 'onScrOll.marginTop=' . variable_get('onscroll_margin_top', 10) . ';';
      $script .= 'onScrOll.mode="' . variable_get('onscroll_mode', 'sticky') . '";';
      $script .= 'onScrOll.height=' . variable_get('onscroll_height', 250) . ';';
      $script .= 'onScrOll.width=' . variable_get('onscroll_width', 300) . ';';
      $script .= 'onScrOll.reload=' . ((variable_get('onscroll_reload', FALSE) == FALSE) ? 'false' : 'true') . ';';
      drupal_add_js($script, array('scope' => 'footer', 'type' => 'inline'));

      // Add external script.
      $script = variable_get('onscroll_url', ONSCROLL_URL);
      $script .= '?campaignId=' . variable_get('onscroll_campaign_id');
      $script .= '&creativeId=' . variable_get('onscroll_creative_id');
      $script .= '&accountId=' . variable_get('onscroll_account_id');
      drupal_add_js($script, array('scope' => 'footer', 'type' => 'external'));
    }
  }
}
