<?php

function you_might_like_section($node, $type = '') {
	$numNodes = 9;
	$terms = array();
	if (is_object($node)) {
		foreach ($node->field_category['und'] as $t) {
			$terms[] = (int)$t['tid'];
		}
	} else if (is_numeric($node)) {
		if ($type == 'author') {
			$author_id = $node->item_id;
		} else {
			$terms[] = (int)$node;
		}
	}
	$query = new EntityFieldQuery();
	$query->entityCondition('entity_type', 'node');
    $query->entityCondition('bundle', 'blog');
    $query->propertyCondition('status', 1);
	if (isset($nid)) {
		$query->propertyCondition('nid', $nid, '<>');
	}
	if (!empty($terms)) {
		$query->fieldCondition('field_category', 'tid', $terms, 'IN');
	}
	if (isset($author_id)) {
		$query->fieldCondition('field_author', 'value', (int)$author_id,'=');
	}
	$query->range(NULL, $numNodes*3);
    $entities = reset($query->execute());
	$keys = array_rand($entities,$numNodes);
	// ob_start();
	echo '<div id="related"><ul><li>';
	$idx = 0;
	foreach ($keys as $key) {
		$node = node_load($entities[$key]->nid);
		if ($idx > 0 && $idx%3 == 0) {
			echo '</li><li>';
		}
	?>
					<div class="box_wrap">
						<div class="relbox">
							<a href="/node/<?php echo $node->nid ?>" class="image">
								<?php echo_article_image($node); ?>
							</a>
							<h2 class="related_a_title"><a href="/node/<?php echo $node->nid ?>"><?php echo $node->title; ?></a></h2>
							<span><?php print $node->field_description['und'][0]['value']; ?></span>
							
						</div><!-- /box -->
						<div class="bottom_shadow"></div>
					</div><!-- /box_wrap  -- next box -> -->
	<?php
		$idx++;
	}
		echo '</li></ul></div>';
		?>
		<script type="text/javascript">
			jQuery.noConflict();
			jQuery(document).ready(function(){
				jQuery("#related").easySlider({
					auto: true,
					continuous: true,
					nextId: "next",
					prevId: "prev",
					prevText: '<'+"div class='prev'><"+"/div>",
					nextText: '<'+"div class='next'><"+"/div>",
					controlsBefore:	'<'+'div class="controls">',
					controlsAfter: '<'+'/div>',
					pause:	10000,
					speed: 1200
				});
			});	
		</script>
		<?php
	
	// $html = ob_get_clean();
	// ob_end_clean();
	return '';
}


?>